### ISSUE TITLE
잘보고 갑니다 ㅎㅎ

### ISSUE THREAD

**Issue by na86421** [blacktokki/tokki-tok#10]
잘보고 갑니당
보다보니 몇개 궁금한게 생겼네요.

1. DB를 공유하는 마이크로서비스 인 것 같은데 User 테이블이 변경되면 Django 쪽에서는 바로 변경이 반영되나요? 아니면 추가 작업이 필요하나요?
2. 어카운트 서비스랑 Messenger 서비스는 어떤 방식으로 통신하고 있나요??
3. Redis pub/sub 부분은 어디에 있을까요 ㅎㅎ..

여러모로 재밌는 코드 많이 보고 갑니다. 동혁씨 :) 

-윤준기

**Comment by blacktokki** [comment]
> 잘보고 갑니당 보다보니 몇개 궁금한게 생겼네요.
> 
> 1. DB를 공유하는 마이크로서비스 인 것 같은데 User 테이블이 변경되면 Django 쪽에서는 바로 변경이 반영되나요? 아니면 추가 작업이 필요하나요?
> 2. 어카운트 서비스랑 Messenger 서비스는 어떤 방식으로 통신하고 있나요??
> 3. Redis pub/sub 부분은 어디에 있을까요 ㅎㅎ..
> 
> 여러모로 재밌는 코드 많이 보고 갑니다. 동혁씨 :)
> 
> -윤준기

1. Account db의 User 테이블 변경시 해당 테이블을 기반으로 만든 Messenger db의 User view 테이블에 영향이 있을 경우 추가 작업이 있을 수 있습니다.
2. Messenger 서버에서 JWT 토큰을 발급하기 위해 Account 서버의 api에 요청하는 [requests.py](https://github.com/blacktokki/tokki-tok/blob/main/messenger-service/accounts/requests.py) 모듈이 있습니다.
3. Django Channel의 ChannelLayer에 [RedisPubSubChannelLayer](https://github.com/blacktokki/tokki-tok/blob/2f27e542e3f400ff4b449635c0cbfd5fb2bb17a8/messenger-service/backend/settings.py#L93C1-L100C2)를 사용합니다.
